server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html

  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: 'jdbc:h2:mem:test;MODE=MySQL'
#    url: 'jdbc:h2:~/data/tarot;MODE=MySQL'
    url: 'jdbc:mysql://localhost:3306/tarot?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul'
    username: root
    password: sasa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        encoding: UTF-8
  sql:
    init:
      mode: always
      encoding: UTF-8


    #    prefix: classpath:/templates/
#    prefix: file:src/main/resources/templates/
#    suffix: .html
#  devtools:
#    restart:
#      enabled: true
#    livereload:
#      enabled: true
jwt:
  secret: and0dGVzdGp3dHRlc3Rqd3R0ZXN0and0dGVzdGp3dHRlc3Q=
  accessToken:
    validityInMinutes: 60

springdoc:
  packages-to-scan: com.tarot.controller
  paths-to-match: /**
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /tarot/swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha